/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CountrySearch.java
 *
 * Created on Nov 10, 2010, 3:53:08 AM
 */

package countries;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.xml.xquery.*;
import net.sf.saxon.xqj.SaxonXQDataSource;

/**
 *
 * @author Al-Jarhi
 */
public class CountrySearch extends javax.swing.JFrame {

    /** Creates new form CountrySearch */
    public CountrySearch() {
        initComponents();
    }

       private String QS()
    {
           String qs = "";

        if(jCheckBox1.isSelected())
        {
            if((CtryN.getText().trim()).equals(""))
            {
               jOptionPane1.showMessageDialog(CountryInformationView.CS, "Country Name field is left blank!", "ERROR!", 0);
               return "";
            }
            qs = qs + "name =\"" + CtryN.getText().trim() + "\" and ";
        }

        if(jCheckBox2.isSelected())
        {
              if((CtyN.getText().trim()).equals(""))
            {
               jOptionPane1.showMessageDialog(CountryInformationView.CS, "City Name field is left blank!", "ERROR!", 0);
               return "";
            }
            qs = qs + "city =\"" + CtyN.getText().trim() + "\"  and ";
        }

        if(jCheckBox3.isSelected())
        {
          if(jCheckBox4.isSelected())
          {
                if((RN.getText().trim()).equals(""))
            {
               jOptionPane1.showMessageDialog(CountryInformationView.CS, "Religion Name field is left blank!", "ERROR!", 0);
               return "";
            }
                   if((RP.getText().trim()).equals(""))
              {
                  jOptionPane1.showMessageDialog(CountryInformationView.CS, "Religion Percentage field is left blank!", "ERROR!", 0);
                  return "";
              }

            qs = qs + "religions[text() =\"" + RN.getText().trim() + "\"]/@percentage" + (String)RPE.getSelectedItem() + RP.getText().trim() + " and ";
          }
         else
         {
                if((RN.getText().trim()).equals(""))
            {
               jOptionPane1.showMessageDialog(CountryInformationView.CS, "Religion Name field is left blank!", "ERROR!", 0);
               return "";
            }
            qs = qs + "religions =\"" + RN.getText().trim() + "\"  and ";
         }
        }

        if(jCheckBox5.isSelected())
        {
              if((PG.getText().trim()).equals(""))
            {
               jOptionPane1.showMessageDialog(CountryInformationView.CS, "Population growth field is left blank!", "ERROR!", 0);
               return "";
            }
            qs = qs + "population/@growth " + (String)PGE.getSelectedItem() + PG.getText().trim() + " and ";
        }

        if(jCheckBox6.isSelected())
        {
              if((P.getText().trim()).equals(""))
            {
               jOptionPane1.showMessageDialog(CountryInformationView.CS, "Population field is left blank!", "ERROR!", 0);
               return "";
            }
            qs = qs + "population " + (String)PE.getSelectedItem() + P.getText().trim() + " and ";
        }

        if(jCheckBox7.isSelected())
        {
              if((G.getText().trim()).equals(""))
            {
               jOptionPane1.showMessageDialog(CountryInformationView.CS, "Government field is left blank!", "ERROR!", 0);
               return "";
            }
            qs = qs + "government =\"" + G.getText().trim() + "\"" + " and ";
        }
           if(qs.equals(""))
           {
              jOptionPane1.showMessageDialog(CountryInformationView.CS, "No search parameter is selected!", "ERROR!", 0);
           }
           else
           {
              qs = "<countries> \n { \n let $ctrs := doc('"+CXML+"')//country[" + qs.substring(0, qs.length()-5) + "] \n \n return $ctrs \n } \n </countries>";
           }
       return qs;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        CtryN = new javax.swing.JTextField();
        CtyN = new javax.swing.JTextField();
        RN = new javax.swing.JTextField();
        RP = new javax.swing.JTextField();
        P = new javax.swing.JTextField();
        PG = new javax.swing.JTextField();
        G = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        PGE = new javax.swing.JComboBox();
        RPE = new javax.swing.JComboBox();
        PE = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setName("jFrame1"); // NOI18N

        jScrollPane2.setAlignmentY(JScrollPane.LEFT_ALIGNMENT);
        jScrollPane2.setName("jScrollPane2"); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(222, 802));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jTextArea1.setPreferredSize(new java.awt.Dimension(220, 800));
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane1.setAlignmentY(JScrollPane.RIGHT_ALIGNMENT);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jEditorPane1.setContentType("text/xml");
        jEditorPane1.setName("jEditorPane1"); // NOI18N
        jEditorPane1.setPreferredSize(new java.awt.Dimension(550, 800));
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );

        jOptionPane1.setName("jOptionPane1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(countries.CountryInformation.class).getContext().getResourceMap(CountrySearch.class);
        CtryN.setText(resourceMap.getString("CtryN.text")); // NOI18N
        CtryN.setName("CtryN"); // NOI18N
        CtryN.setVisible(false);

        CtyN.setText(resourceMap.getString("CtyN.text")); // NOI18N
        CtyN.setName("CtyN"); // NOI18N
        CtyN.setVisible(false);

        RN.setText(resourceMap.getString("RN.text")); // NOI18N
        RN.setName("RN"); // NOI18N
        RN.setVisible(false);

        RP.setText(resourceMap.getString("RP.text")); // NOI18N
        RP.setName("RP"); // NOI18N
        RP.setVisible(false);

        P.setText(resourceMap.getString("P.text")); // NOI18N
        P.setName("P"); // NOI18N
        P.setVisible(false);

        PG.setText(resourceMap.getString("PG.text")); // NOI18N
        PG.setName("PG"); // NOI18N
        PG.setVisible(false);

        G.setText(resourceMap.getString("G.text")); // NOI18N
        G.setName("G"); // NOI18N
        G.setVisible(false);

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setVisible(false);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        PGE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", ">", "<" }));
        PGE.setName("PGE"); // NOI18N
        PGE.setVisible(false);

        RPE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", ">", "<" }));
        RPE.setName("RPE"); // NOI18N
        RPE.setVisible(false);

        PE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", ">", "<" }));
        PE.setName("PE"); // NOI18N
        PE.setVisible(false);

        jCheckBox1.setFont(resourceMap.getFont("jCheckBox1.font")); // NOI18N
        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jCheckBox2.setFont(resourceMap.getFont("jCheckBox2.font")); // NOI18N
        jCheckBox2.setText(resourceMap.getString("jCheckBox2.text")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });

        jCheckBox3.setFont(resourceMap.getFont("jCheckBox3.font")); // NOI18N
        jCheckBox3.setText(resourceMap.getString("jCheckBox3.text")); // NOI18N
        jCheckBox3.setName("jCheckBox3"); // NOI18N
        jCheckBox3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox3StateChanged(evt);
            }
        });
        jCheckBox3.setLocation(jCheckBox3.getLocation());

        jCheckBox4.setFont(resourceMap.getFont("jCheckBox4.font")); // NOI18N
        jCheckBox4.setText(resourceMap.getString("jCheckBox4.text")); // NOI18N
        jCheckBox4.setName("jCheckBox4"); // NOI18N
        jCheckBox4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox4StateChanged(evt);
            }
        });
        jCheckBox4.setVisible(false);

        jCheckBox5.setFont(resourceMap.getFont("jCheckBox5.font")); // NOI18N
        jCheckBox5.setText(resourceMap.getString("jCheckBox5.text")); // NOI18N
        jCheckBox5.setName("jCheckBox5"); // NOI18N
        jCheckBox5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox5StateChanged(evt);
            }
        });
        jCheckBox5.setLocation(jCheckBox5.getLocation());

        jCheckBox6.setFont(resourceMap.getFont("jCheckBox6.font")); // NOI18N
        jCheckBox6.setText(resourceMap.getString("jCheckBox6.text")); // NOI18N
        jCheckBox6.setName("jCheckBox6"); // NOI18N
        jCheckBox6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox6StateChanged(evt);
            }
        });
        jCheckBox6.setLocation(jCheckBox6.getLocation());

        jCheckBox7.setFont(resourceMap.getFont("jCheckBox7.font")); // NOI18N
        jCheckBox7.setText(resourceMap.getString("jCheckBox7.text")); // NOI18N
        jCheckBox7.setName("jCheckBox7"); // NOI18N
        jCheckBox7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox7StateChanged(evt);
            }
        });
        jCheckBox7.setLocation(jCheckBox7.getLocation());

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CtryN, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CtyN, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RN, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PGE, 0, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PG, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(G, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RPE, 0, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RP, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(CtryN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(CtyN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(RN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(PG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(PE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        CtryN.setVisible(jCheckBox1.isSelected());
         CountryInformationView.CS.validate();
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        // TODO add your handling code here:
        CtyN.setVisible(jCheckBox2.isSelected());
        CountryInformationView.CS.validate();
    }//GEN-LAST:event_jCheckBox2StateChanged

    private void jCheckBox3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox3StateChanged
        // TODO add your handling code here:
        RN.setVisible(jCheckBox3.isSelected());
        jCheckBox4.setVisible(jCheckBox3.isSelected());
        jLabel8.setVisible(jCheckBox3.isSelected());
        if(!jCheckBox3.isSelected())
        {
            jCheckBox4.setSelected(false);
        }
        CountryInformationView.CS.validate();
    }//GEN-LAST:event_jCheckBox3StateChanged

    private void jCheckBox4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox4StateChanged
        // TODO add your handling code here:
        RP.setVisible(jCheckBox4.isSelected());
        RPE.setVisible(jCheckBox4.isSelected());
        CountryInformationView.CS.validate();
    }//GEN-LAST:event_jCheckBox4StateChanged

    private void jCheckBox5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox5StateChanged
        // TODO add your handling code here:
        PG.setVisible(jCheckBox5.isSelected());
        PGE.setVisible(jCheckBox5.isSelected());
        CountryInformationView.CS.validate();
    }//GEN-LAST:event_jCheckBox5StateChanged

    private void jCheckBox6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox6StateChanged
        // TODO add your handling code here:
        P.setVisible(jCheckBox6.isSelected());
        PE.setVisible(jCheckBox6.isSelected());
        CountryInformationView.CS.validate();
    }//GEN-LAST:event_jCheckBox6StateChanged

    private void jCheckBox7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox7StateChanged
        // TODO add your handling code here:
        G.setVisible(jCheckBox7.isSelected());
        CountryInformationView.CS.validate();
    }//GEN-LAST:event_jCheckBox7StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
             // TODO add your handling code here:
            String XQ = QS();
            if(XQ.equals(""))
            return;
            // load the XQDataSource instance
            XQDataSource xqs = new SaxonXQDataSource();
            // create an XQConnection
            Properties serializationProps = new java.util.Properties();
            // make sure we output xml
            serializationProps.setProperty("method", "xml");
            // pretty printing
            serializationProps.setProperty("indent", "yes");
            // serialize as UTF-8
            serializationProps.setProperty("encoding", "UTF-8");
            // want an XML declaration
            serializationProps.setProperty("omit-xml-declaration", "no");
         
            XQConnection xqc = xqs.getConnection();
            XQExpression xqe;
            xqe = xqc.createExpression();
            XQSequence rs = xqe.executeQuery(XQ);

            StringWriter HO = new StringWriter();
            BufferedWriter ho = new BufferedWriter(HO);

            rs.writeSequence(ho, serializationProps);

              if((HO.toString()).endsWith("<countries/>"))
            {
               CountryInformationView.CS.dispose();
               CountryInformation.getApplication().getMainFrame().setEnabled(true);
               jOptionPane1.showMessageDialog(CountryInformation.getApplication().getMainFrame(), "No result!", "Info", 1);
                return;
            }
         
            BufferedReader CtryNS = new BufferedReader(new StringReader(HO.toString()));

        String Reader;

        int c = 4; // no of rows

        jTextArea1.setText("Results \n\n"+ "Countries: \n\n");


        while((Reader = CtryNS.readLine()) != null)
        {
          Reader = Reader.trim();
          if((Reader).startsWith("<name>"))
          {
              c = c+2;
              jTextArea1.append(Reader.substring(6, Reader.length()-7) + "\n \n");
          }
        }
        CtryNS.close();

            jTextArea1.setRows(c);
            jTextArea1.setEditable(false);

            jEditorPane1.setText(HO.toString());
            jEditorPane1.setEditable(false);

            jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

          
            jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

            jFrame1.pack();
            jFrame1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            jFrame1.setLocationRelativeTo(CountryInformation.getApplication().getMainFrame());
            jFrame1.setResizable(false);

            }catch (Exception ex) {
            Logger.getLogger(CountrySearch.class.getName()).log(Level.SEVERE, null, ex);
        }
            CountryInformation.getApplication().getMainFrame().setEnabled(true);
            CountryInformationView.CS.dispose();
            jFrame1.setVisible( true );    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CtryN;
    private javax.swing.JTextField CtyN;
    private javax.swing.JTextField G;
    private javax.swing.JTextField P;
    private javax.swing.JComboBox PE;
    private javax.swing.JTextField PG;
    private javax.swing.JComboBox PGE;
    private javax.swing.JTextField RN;
    private javax.swing.JTextField RP;
    private javax.swing.JComboBox RPE;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private static final String CXML = "F:/Stuff/Muaz/GUC/Semi-Structured Data and the Web/countries.xml";
}
