/*
 * DesktopApplication1AboutBox.java
 */

package desktopapplication1;

import org.jdesktop.application.Action;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.SwingUtilities;


public  class  DesktopApplication1Addfile  extends javax.swing.JFrame {
    protected static int returnVal;  
    String multi;
    public  DesktopApplication1Addfile() {
         
        initComponents();
        jFileChooser1.setMultiSelectionEnabled(true);
        returnVal = jFileChooser1.showOpenDialog(DesktopApplication1Addfile.this);      
       
    }
    
    
        /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        jFileChooser1.setName("jFileChooser1"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jFileChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jFileChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
  
 private void setModal(boolean b) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
}
