/*
 * Download.java
 *
 * Created on 09 February 2008, 21:46
 */

package desktopapplication1;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.regex.*;
import javax.swing.JFrame;
import org.jdesktop.application.Action;
import sun.nio.ch.SocketAdaptor;
/**
 *
 * @author  Amd
 */

public class Download extends javax.swing.JFrame {
 
    DatagramSocket s;
    String filename, initString;
    byte[] buffer;
    DatagramPacket initPacket, receivedPacket;
    FileOutputStream fileWriter;
    int bytesReceived, bytesToReceive;
    
    
    List resultList;
    /** Creates new form Download */
    public Download(List p_List) {
        initComponents();
        resultList = p_List;
      
             jList1.setListData(resultList.toArray());
              jList1.repaint();
              
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getActionMap(Download.class, this);
        jButton1.setAction(actionMap.get("download")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getResourceMap(Download.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(94, 94, 94)
                        .add(jButton1))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(115, 115, 115)
                        .add(jLabel1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton1)
                .add(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    @Action
    public void download()
    {
   Object [] filez = jList1.getSelectedValues();
    for(int i = 0; i <filez.length; i++)
    {    
    String [] file = filez[i].toString().split(" ");
    buffer = new byte[8192];	
    filename = "C:\\Documents and Settings\\Amd\\My Documents\\" + filez[i];
      PrintWriter Out;
      Socket client;
      try
      {
      client = new Socket(filez[1].toString(),10102);
           Out = new PrintWriter(client.getOutputStream(), true);
           Out.println(("UPLOAD TO " + Helpers.MyIP() + " File " + file[0]));
      }catch (UnknownHostException e){} catch (Exception e){}
	
    //Receive the contents of the file
    try
    {
	fileWriter = new FileOutputStream(filename);

    while(bytesReceived < bytesToReceive)
	    {
		receivedPacket = receivePacket();
		fileWriter.write(receivedPacket.getData(), 0,  receivedPacket.getLength());
		bytesReceived = bytesReceived + receivedPacket.getLength();
	    }
    }
    catch (Exception e)
    {
    }
   
    setVisible(false);
    }
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Download( ).setVisible(true);
            }
        });
    }
    
    
    
    
    public DatagramPacket receivePacket() throws IOException{
	
	DatagramPacket packet = 
	    new DatagramPacket(buffer, buffer.length);
	s.receive(packet);
	
	return packet;
    }
    
    public byte[] receiveData() throws IOException{

	DatagramPacket packet = 
	    new DatagramPacket(buffer, buffer.length);
	s.receive(packet);
	
	return packet.getData();
    }

    public void send(InetAddress recv, int port,byte[] message)
       throws IOException {
      
	//InetAddress recv = InetAddress.getByName(host);
       DatagramPacket packet = 
	   new DatagramPacket(message, message.length, recv, port);
       s.send(packet);
   }	
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    protected static javax.swing.JLabel jLabel1;
    protected static javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
